### ISSUE TITLE
The loss implemented in Inter_class_layer seems to be different from the MHE loss form on paper

### ISSUE THREAD

**Issue by jay2002** [wy1iu/sphereface-plus#3]
As stated. Any explanation?

**Comment by wy1iu** [comment]
We did a mini-batch approximation to MHE loss, because if you compute the original MHE loss on datasets with many identities (CASIA has over 10 thousand identities), you will have to perform pair-wise similarity between 10000 classifiers (equivalent to computing a pair-wise matrix which is of size 10000 by 10000). It can be quite computationally costly. 

What we did here is to essentially perform a mini-batch approximation to the original MHE loss, which we describe in the section 3.6. There might be some other minor modifications due to implementation convenience and computation reduction, but they do not affect the original intuition and formulation. The most crucial part is just the mini-batch approximation.

**Comment by jay2002** [comment]
Hi @wy1iu， thx for your reply.
I have noticed the mini-batch approximation part, but what confused me is the fp part in inter_class_layer.cpp/cu is  more like to maximize /sigma ||w_yi - w_j || ^ 2 (which is totally different to minimize /sigma ||w_yi - w_j || ^ -2), and the bp part is also not very clear.
In addition, the normalization for weights seems ignored in the codes.
Can you give some formulations about the actual implementation?

**Comment by liulixinkerry** [comment]
Hi @jay2002 
Thx for your suggestion. Our MHE loss(alias inter class loss) is `/sigma (||w_i - w_j || ^ -2)`. But here, for accelerated GPU computation, we use `(/sigma ||w_i - w_j || ^ 2) ^ -1`. And the inter class distance is `/sigma ||w_i - w_j || ^ 2`. 

We choose to output the inter class distance in the log but not the MHE loss because we want to reduce calculation in GPU version and monitor interclass distance more easily while MHE loss is too small to monitor. So the fp is `(/sigma ||w_i - w_j || ^ 2) ^ -1` but the output in the log is `/sigma ||w_i - w_j || ^ 2`. 

As for your confusion, you can see the comment in [the old version of inter_class_layer.cu #117 ](https://github.com/wy1iu/sphereface-plus/blame/183533ae64ee6413097088b153dbaebf5e93b394/tools/caffe-sfplus/src/caffe/layers/inter_class_layer.cu#L117). I am sorry that parameter names there aren't rigorous. I have revised `inter_class_loss` to `inter_class_dist` in the **newest** version, pls check.

Weight is normalized in margin inner product layer, check [WN in margin_inner_product_layer.cpp](https://github.com/wy1iu/sphereface-plus/blob/9db39d7af175ba11612bb0d2e76fa1c553a2c468/tools/caffe-sfplus/src/caffe/layers/margin_inner_product_layer.cpp#L121) and [WN in margin_inner_product_layer.cu](https://github.com/wy1iu/sphereface-plus/blob/9db39d7af175ba11612bb0d2e76fa1c553a2c468/tools/caffe-sfplus/src/caffe/layers/margin_inner_product_layer.cu#L272).

**Comment by jay2002** [comment]
Is /sigma ||w_i - w_j || ^ -2 equal to pow(/sigma ||w_i - w_j || ^ 2, -1)?...

**Comment by liulixinkerry** [comment]
Hi @jay2002 
No, they are not the same. However, [Jensen Inequality](https://en.wikipedia.org/wiki/Jensen%27s_inequality)'s special case (AM-GM-HM Inequality) gives us `/sigma (||w_i - w_j ||  ^  -2) >= pow(/sigma ||w_i - w_j ||  ^  2, -1)` so these two formulations' opimization are essentially similar, both of them are for **weight diverseness**, which is the core of MHE. Actually, the latter's GPU calculation is much faster than the former.

Loss:
```
L_{in}=\frac{1}{\frac{1}{N}\sum\limits_{i=label[0]}^{label[M-1]}\sum\limits_{j=0}^{N-1}\left | \left | W_i-W_j \right |\right|_2^2}  
```
![Loss](https://quicklatex.com/cache3/3e/ql_81d814d3854aacfc0d9e7ccf651cdf3e_l3.png)
Optimization:
```
W_{total}&=\frac{\sum\limits_{i=0}^{N-1} W_i}{\left|\left|\sum\limits_{i=0}^{N-1} W_i\right|\right|}\\  
\frac{\partial{L_{in}}}{\partial W_k}&=\sum\limits_{i=label[0] }^{label[M-1]}(i==k)*\frac{-4\alpha}{N\left(\sum\limits_{i=label[0]}^{label[M-1]}\sum\limits_{j=0}^{N-1}\left|\left|W_i-W_j \right|\right|_2^2\right)^2+\epsilon}(W_k-W_{total}) \\   
\epsilon&=1e-5  
```
![Optimization](https://quicklatex.com/cache3/39/ql_071594e5ca0f42e3ac741d43049e6839_l3.png)

`N` in bp isn't so important that I just use if for scaling the gradient. I also normalize `W_total` because of stablizing training.

**Comment by jay2002** [comment]
@liulixinkerry Thx for your reply. Im clear now
